task05 created
grantag2004/tspp_2024 pull request #5
Opened 2024-10-26 23:31 UTC by grantag2004

2024-10-27 07:00 UTC, dimlichmanov requested changes
![изображение](https://github.com/user-attachments/assets/c8bb5e38-0df1-4bc7-9d49-054ce8b271fd)

2024-10-27 12:36 UTC, grantag2004 commented
А что не так, я не очень понял?) Я добавил лишний файл?

2024-10-27 12:44 UTC, dimlichmanov commented
Ага)

2024-10-27 12:50 UTC, grantag2004 commented
Мне его просто удалить или подойти на паре, как в табличке указано?)

2024-10-27 12:51 UTC, dimlichmanov commented
Удалите, тогда я посмотрю программу. можете и на паре удалить, тогда на паре и посмотрю)

2024-10-27 14:02 UTC, dimlichmanov requested changes
Остальное всё ок, запустите тесты через очередь (возможно, придётся отказаться от интерактивного ввода), визуализацию по новым данным можете не править на первый раз.

2024-10-27 14:02 UTC, dimlichmanov commented on task05/Вывод.rtf
> +\f0\fs36 \cf2 \CocoaLigature0 [edu-cmc-sqi24-01@polus-ib ~]$ ./a.out\
А кто будет программу запускать через очередь?)

2024-10-29 15:05 UTC, grantag2004 commented
Я не понимаю, почему .DS_Store виден((

2024-10-29 15:10 UTC, grantag2004 commented
Запустил на очереди, изменения в отчет не вносил(как вы и сказали:) ).

2024-10-29 21:00 UTC, dimlichmanov approved these changes
Видимо, вы залили файлы DS Store до того, как сделали gitignore.
По идее, в следующий коммит они уже не должны добавиться.
Если всё-таки будут добавляться, сделайте потом что-то типа git rm *.DS_Store.

P.S. rtf вывод нечитабелен, к сожалению, но графики вас спасли)

2024-10-30 11:45 UTC, merged